Handle alternate app location.

diff --git a/bin/skim b/bin/skim
--- a/bin/skim
+++ b/bin/skim
@@ -1,3 +1,13 @@
 #!/bin/bash
 
-open -a /Applications/Skim.app "${@}"
+for SKIM in \
+    ~/Applications/Skim.app \
+    /Applications/Skim.app \
+    ; \
+do
+    open -a "${SKIM}" "${@}"
+    exit 0
+done
+echo 'Skim not found!' 1>&2
+exit 1
+
